// <auto-generated />
using System;
using Inventory.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Api.Domain.Entities.FlightInventoryDay", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<Guid>("FlightClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_class_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("inventory_date");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("available_seats");

                    b.Property<int>("ConfirmedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_seats");

                    b.Property<int>("HeldSeats")
                        .HasColumnType("integer")
                        .HasColumnName("held_seats");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("FlightId", "FlightClassId", "Date");

                    b.HasIndex("FlightId", "Date");

                    b.ToTable("flight_inventory_days", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.FlightInventoryHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("flight_inventory_holds", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.FlightInventoryHoldLine", b =>
                {
                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<Guid>("FlightClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_class_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("inventory_date");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("HoldId", "FlightClassId", "Date");

                    b.ToTable("flight_inventory_hold_lines", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.HotelInventoryDay", b =>
                {
                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("inventory_date");

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("integer")
                        .HasColumnName("available_units");

                    b.Property<int>("ConfirmedUnits")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_units");

                    b.Property<int>("HeldUnits")
                        .HasColumnType("integer")
                        .HasColumnName("held_units");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer")
                        .HasColumnName("total_units");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("HotelId", "RoomTypeId", "Date");

                    b.HasIndex("HotelId", "Date");

                    b.ToTable("hotel_inventory_days", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.HotelInventoryHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("hotel_inventory_holds", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.HotelInventoryHoldLine", b =>
                {
                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("inventory_date");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("HoldId", "RoomTypeId", "Date");

                    b.ToTable("hotel_inventory_hold_lines", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.FlightInventoryHoldLine", b =>
                {
                    b.HasOne("Inventory.Api.Domain.Entities.FlightInventoryHold", null)
                        .WithMany("Lines")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.HotelInventoryHoldLine", b =>
                {
                    b.HasOne("Inventory.Api.Domain.Entities.HotelInventoryHold", null)
                        .WithMany("Lines")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.FlightInventoryHold", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Inventory.Api.Domain.Entities.HotelInventoryHold", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
