<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <ProjectReference Include="BuildingBlocks.Contracts\BuildingBlocks.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BuildingBlocks.Contracts\**" />
    <EmbeddedResource Remove="BuildingBlocks.Contracts\**" />
    <None Remove="BuildingBlocks.Contracts\**" />
  </ItemGroup>

</Project>
